In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
from sklearn.preprocessing import OneHotEncoder

Mounted at /content/drive


In [2]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/dataset_merged_processed_no_outliers.csv")

In [3]:
df.head(3)

YEAR  MONTH  DAY  DAY_OF_WEEK ORIGIN_AIRPORT DESTINATION_AIRPORT  \
0  2015      1    1            4            ANC                 SEA   
1  2015      1    1            4            LAX                 PBI   
2  2015      1    1            4            SFO                 CLT   

   SCHEDULED_DEPARTURE  SCHEDULED_TIME  DISTANCE  SCHEDULED_ARRIVAL  ...  \
0                    5           205.0      1448                430  ...   
1                   10           280.0       641                750  ...   
2                   20           286.0       641                806  ...   

   CANCELLATION_REASON ORIGIN_STATE ORIGIN_LATITUDE ORIGIN_LONGITUDE  \
0            No Aplica           AK        61.17432       -149.99619   
1            No Aplica           CA        33.94254       -118.40807   
2            No Aplica           CA        37.61900       -122.37484   

   DESTINATION_STATE  DESTINATION_LATITUDE DESTINATION_LONGITUDE  \
0                 WA              47.44898            -122.30931   
1                 FL              26.68316             -80.09559   
2                 NC              35.21401             -80.94313   

             AIRLINE_NAME  CANCELLED_NUM DEPARTURE_HOUR  
0    Alaska Airlines Inc.              0              0  
1  American Airlines Inc.              0              0  
2         US Airways Inc.              0              0  

[3 rows x 22 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899134 entries, 0 to 899133
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   YEAR                   899134 non-null  int64  
 1   MONTH                  899134 non-null  int64  
 2   DAY                    899134 non-null  int64  
 3   DAY_OF_WEEK            899134 non-null  int64  
 4   ORIGIN_AIRPORT         899134 non-null  object 
 5   DESTINATION_AIRPORT    899134 non-null  object 
 6   SCHEDULED_DEPARTURE    899134 non-null  int64  
 7   SCHEDULED_TIME         899134 non-null  float64
 8   DISTANCE               899134 non-null  int64  
 9   SCHEDULED_ARRIVAL      899134 non-null  int64  
 10  DIVERTED               899134 non-null  int64  
 11  CANCELLED              899134 non-null  object 
 12  CANCELLATION_REASON    899134 non-null  object 
 13  ORIGIN_STATE           899134 non-null  object 
 14  ORIGIN_LATITUDE        899134 non-nu

In [6]:
df.ORIGIN_AIRPORT.unique()

array(['ANC', 'LAX', 'SFO', 'SEA', 'LAS', 'DEN', 'SLC', 'PDX', 'FAI',
       'MSP', 'PHX', 'SJU', 'PBG', 'IAG', 'PSE', 'BQN', 'ORD', 'GEG',
       'HNL', 'ONT', 'MCO', 'BOS', 'HIB', 'ABR', 'MAF', 'DFW', 'MKE',
       'IAH', 'BNA', 'BRO', 'VPS', 'BOI', 'BJI', 'SGF', 'PHL', 'SBN',
       'RDD', 'EUG', 'IAD', 'BUF', 'PWM', 'JFK', 'CRP', 'PIA', 'FAT',
       'SMF', 'AUS', 'MCI', 'ATL', 'JAX', 'MFR', 'IDA', 'MSN', 'DCA',
       'SAT', 'CHS', 'SBA', 'SMX', 'IND', 'CLE', 'GSP', 'BDL', 'ABI',
       'RIC', 'BFL', 'OMA', 'RDM', 'FLL', 'CID', 'TPA', 'SYR', 'ROC',
       'TYR', 'LAN', 'XNA', 'GSO', 'EWR', 'PBI', 'RSW', 'OAK', 'PVD',
       'RNO', 'PIT', 'ABQ', 'MIA', 'BWI', 'LGA', 'TUL', 'LIT', 'MSY',
       'OKC', 'ATW', 'PNS', 'MEM', 'TYS', 'MHT', 'SAV', 'CLT', 'GRB',
       'ABE', 'JAN', 'OAJ', 'FAR', 'ERI', 'LEX', 'CWA', 'MSO', 'TTN',
       'AMA', 'CLL', 'HOU', 'JLN', 'MLI', 'RDU', 'CVG', 'MHK', 'MOB',
       'TLH', 'BHM', 'CAE', 'TXK', 'ACY', 'DTW', 'RAP', 'TUS', 'EAU',
       'DLH', 'FSD',

In [7]:
df.DESTINATION_AIRPORT.unique()

array(['SEA', 'PBI', 'CLT', 'MIA', 'ANC', 'MSP', 'DFW', 'ATL', 'IAH',
       'PDX', 'MCI', 'FLL', 'ORD', 'HNL', 'PHX', 'EWR', 'JFK', 'MCO',
       'BOS', 'BDL', 'ITO', 'SFO', 'KOA', 'OGG', 'MYR', 'DTW', 'LIH',
       'DEN', 'SJU', 'LAX', 'BWI', 'IAD', 'BQN', 'BUF', 'LGA', 'HOU',
       'SLC', 'PHL', 'SJC', 'OAK', 'LGB', 'TPA', 'DCA', 'TTN', 'BTR',
       'LAS', 'RSW', 'BRD', 'STL', 'RKS', 'MBS', 'SNA', 'MEI', 'MDW',
       'SAN', 'RIC', 'AUS', 'OTZ', 'PIT', 'JAX', 'MSY', 'ONT', 'PSP',
       'BUR', 'DAL', 'CVG', 'SMF', 'RDU', 'JMS', 'BNA', 'DSM', 'MAF',
       'BOI', 'ELP', 'TUS', 'SCC', 'HPN', 'STT', 'MDT', 'RHI', 'SBP',
       'MKE', 'JNU', 'CMH', 'CLD', 'KTN', 'CAK', 'CRP', 'CLE', 'GPT',
       'SHV', 'TYS', 'IND', 'LIT', 'SAT', 'SRQ', 'TUL', 'GRK', 'PNS',
       'BTV', 'CHS', 'DAY', 'OKC', 'SAV', 'XNA', 'COS', 'GJT', 'BZN',
       'PUB', 'HRL', 'HDN', 'MEM', 'GEG', 'ORH', 'SYR', 'GSO', 'VPS',
       'LAW', 'ACY', 'LBB', 'JAC', 'BIL', 'EUG', 'ASE', 'TVC', 'MTJ',
       'CAE', 'PVD',

In [8]:
df.CANCELLED.unique()

array(['No Cancelado', 'Cancelado'], dtype=object)

In [9]:
df.CANCELLATION_REASON.unique()

array(['No Aplica', 'Airline', 'Weather', 'National Air System',
       'Security'], dtype=object)

In [10]:
df.ORIGIN_STATE.unique()

array(['AK', 'CA', 'WA', 'NV', 'CO', 'UT', 'OR', 'MN', 'AZ', 'PR', 'NY',
       'IL', 'HI', 'FL', 'MA', 'SD', 'TX', 'WI', 'TN', 'ID', 'MO', 'PA',
       'IN', 'VA', 'ME', 'GA', 'SC', 'OH', 'CT', 'NE', 'IA', 'MI', 'AR',
       'NC', 'NJ', 'RI', 'NM', 'MD', 'OK', 'LA', 'NH', 'MS', 'ND', 'KY',
       'MT', 'KS', 'AL', 'WY', 'VT', 'GU', 'VI', 'WV', 'DE', 'AS'],
      dtype=object)

In [11]:
df.DESTINATION_STATE.unique()

array(['WA', 'FL', 'NC', 'AK', 'MN', 'TX', 'GA', 'OR', 'MO', 'IL', 'HI',
       'AZ', 'NJ', 'NY', 'MA', 'CT', 'CA', 'SC', 'MI', 'CO', 'PR', 'MD',
       'VA', 'UT', 'PA', 'LA', 'NV', 'WY', 'MS', 'KY', 'ND', 'TN', 'IA',
       'ID', 'VI', 'WI', 'OH', 'IN', 'AR', 'OK', 'VT', 'MT', 'RI', 'AL',
       'NM', 'NE', 'KS', 'SD', 'ME', 'NH', 'WV', 'DE', 'GU', 'AS'],
      dtype=object)

In [12]:
df.YEAR.unique()

array([2015])

In [13]:
df.DAY.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [14]:
df.DAY_OF_WEEK.unique()

array([4, 5, 6, 7, 1, 2, 3])

In [15]:
df.MONTH.unique()

array([1, 2])

In [16]:
df.DISTANCE.unique()

array([1448,  641, 1589, ...,  660,  443, 1128])

In [17]:
df.SCHEDULED_ARRIVAL.unique()

array([430, 750, 806, ..., 310, 206, 248])

In [18]:
df["CANCELLED"] = df["CANCELLED"].replace({"No Cancelado":0, "Cancelado":1})

/tmp/ipython-input-374702065.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["CANCELLED"] = df["CANCELLED"].replace({"No Cancelado":0, "Cancelado":1})


In [19]:
df["MONTH"] = df["MONTH"].replace({"1":0, "2":1})

In [20]:
region_map = {
    'ME': 'Noreste', 'NH': 'Noreste', 'VT': 'Noreste', 'MA': 'Noreste', 'RI': 'Noreste',
    'CT': 'Noreste', 'NY': 'Noreste', 'NJ': 'Noreste', 'PA': 'Noreste',

    'OH': 'MedioOeste', 'MI': 'MedioOeste', 'IN': 'MedioOeste', 'IL': 'MedioOeste', 'WI': 'MedioOeste',
    'MN': 'MedioOeste', 'IA': 'MedioOeste', 'MO': 'MedioOeste', 'ND': 'MedioOeste', 'SD': 'MedioOeste',
    'NE': 'MedioOeste', 'KS': 'MedioOeste',

    'DE': 'Sur', 'MD': 'Sur', 'DC': 'Sur', 'VA': 'Sur', 'WV': 'Sur', 'KY': 'Sur', 'TN': 'Sur',
    'NC': 'Sur', 'SC': 'Sur', 'GA': 'Sur', 'FL': 'Sur', 'AL': 'Sur', 'MS': 'Sur', 'AR': 'Sur',
    'LA': 'Sur', 'OK': 'Sur', 'TX': 'Sur',

    'MT': 'Oeste', 'ID': 'Oeste', 'WY': 'Oeste', 'CO': 'Oeste', 'NM': 'Oeste', 'AZ': 'Oeste', 'UT': 'Oeste',
    'NV': 'Oeste', 'WA': 'Oeste', 'OR': 'Oeste', 'CA': 'Oeste', 'HI': 'Oeste', 'AK': 'Oeste',

    'PR': 'Territorios', 'VI': 'Territorios', 'GU': 'Territorios', 'AS': 'Territorios'
}


df['ORIGIN_REGION'] = df['ORIGIN_STATE'].map(region_map)
df['DESTINATION_REGION'] = df['DESTINATION_STATE'].map(region_map)

In [21]:
df.ORIGIN_REGION.unique()

array(['Oeste', 'MedioOeste', 'Territorios', 'Noreste', 'Sur'],
      dtype=object)

In [22]:
df.DESTINATION_REGION.unique()

array(['Oeste', 'Sur', 'MedioOeste', 'Noreste', 'Territorios'],
      dtype=object)

In [23]:
top_origin = df['ORIGIN_AIRPORT'].value_counts().nlargest(20).index
df['ORIGIN_AIRPORT_REDUCED'] = df['ORIGIN_AIRPORT'].where(df['ORIGIN_AIRPORT'].isin(top_origin), 'OTROS')


top_dest = df['DESTINATION_AIRPORT'].value_counts().nlargest(20).index
df['DESTINATION_AIRPORT_REDUCED'] = df['DESTINATION_AIRPORT'].where(df['DESTINATION_AIRPORT'].isin(top_dest), 'OTROS')


In [24]:
columnas_cat = ['ORIGIN_AIRPORT_REDUCED', 'DESTINATION_AIRPORT_REDUCED',
                'ORIGIN_REGION', 'DESTINATION_REGION']

In [25]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [26]:
ohe.fit(df[columnas_cat])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [27]:
df_encoded = ohe.transform(df[columnas_cat])

In [28]:
columnas_ohe = ohe.get_feature_names_out(columnas_cat)
df_ohe = pd.DataFrame(df_encoded, columns=columnas_ohe, index=df.index)

In [29]:
df_final = pd.concat([df.drop(columns=columnas_cat), df_ohe], axis=1)

In [30]:
df_final.head()

YEAR  MONTH  DAY  DAY_OF_WEEK ORIGIN_AIRPORT DESTINATION_AIRPORT  \
0  2015      1    1            4            ANC                 SEA   
1  2015      1    1            4            LAX                 PBI   
2  2015      1    1            4            SFO                 CLT   
3  2015      1    1            4            LAX                 MIA   
4  2015      1    1            4            SEA                 ANC   

   SCHEDULED_DEPARTURE  SCHEDULED_TIME  DISTANCE  SCHEDULED_ARRIVAL  ...  \
0                    5           205.0      1448                430  ...   
1                   10           280.0       641                750  ...   
2                   20           286.0       641                806  ...   
3                   20           285.0       641                805  ...   
4                   25           235.0      1448                320  ...   

   ORIGIN_REGION_MedioOeste  ORIGIN_REGION_Noreste ORIGIN_REGION_Oeste  \
0                       0.0                    0.0                 1.0   
1                       0.0                    0.0                 1.0   
2                       0.0                    0.0                 1.0   
3                       0.0                    0.0                 1.0   
4                       0.0                    0.0                 1.0   

  ORIGIN_REGION_Sur  ORIGIN_REGION_Territorios  DESTINATION_REGION_MedioOeste  \
0               0.0                        0.0                            0.0   
1               0.0                        0.0                            0.0   
2               0.0                        0.0                            0.0   
3               0.0                        0.0                            0.0   
4               0.0                        0.0                            0.0   

  DESTINATION_REGION_Noreste  DESTINATION_REGION_Oeste  \
0                        0.0                       1.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       1.0   

   DESTINATION_REGION_Sur DESTINATION_REGION_Territorios  
0                     0.0                            0.0  
1                     1.0                            0.0  
2                     1.0                            0.0  
3                     1.0                            0.0  
4                     0.0                            0.0  

[5 rows x 74 columns]

In [31]:
df.shape

(899134, 26)

In [32]:
df_final.to_csv("/content/drive/MyDrive/Datasets/dataset_merged_processed_no_outliers_numeric.csv", index=False)